### ISSUE TITLE
3DSident returns instantly to HOME Menu with headphones inserted

### ISSUE THREAD

**Issue by Clement95** [joel16/3DSident#11]
When headphones are inserted, I think 3DSident believes that a button is pressed so it returns to the HOME Menu.

**Comment by joel16** [comment]
Just tried this on my 3DS, and this doesn't seem to happen.
Are you using the original version or GUI? I'm assuming it would be the original.
Also does your headphones have buttons, because I just tried mine and if I use the buttons on the headphones, the original version exits thinking a button is pressed.

**Comment by Clement95** [comment]
Sorry I wanted to say earphones I confused with a headphones (I am
French), my headphones have buttons but I don't press on it, I tried
with a headphones that has no buttons and my console doesn't return to
HOME Menu

**Comment by joel16** [comment]
Then it might be that your other earphones are causing it, and not a bug in the program itself.

**Comment by Clement95** [comment]
The problem comes from earphones, but I don't have any problems with the +
and - buttons and also the one that answers calls when the headphones are
used on a phone, everything works perfectly.

2017-06-11 16:47 GMT+02:00 Joel <notifications@github.com>:

**Comment by joel16** [comment]
I'll see what I can do, I may just have to avoid using headphone buttons, and stick with any key on the 3DS

**Comment by Clement95** [comment]
Ok, thank you !

2017-06-11 17:29 GMT+02:00 Joel <notifications@github.com>:

**Comment by Clement95** [comment]
Otherwise, thank you! The software has served me more than once and good
luck to improve it :)

2017-06-11 17:30 GMT+02:00 Clément <clement9555@gmail.com>:

**Comment by joel16** [comment]
Try this and let me know if it works. If it doesn't then it must be something with your earphones, and not something I can fix from my side.

3dsx https://mega.nz/#!qYAh0bIB!j8BhRG1rbHWX4XemiP2U1ZfF4zn4OWd7botbidFVSLo

CIA https://mega.nz/#!2NpEVLxJ!GZaSby9xviBY3YyIGxzrO3GUnTQMnOXxZY_RYrrQZwM

**Comment by Clement95** [comment]
It works perfectly thank you !

2017-06-11 18:35 GMT+02:00 Joel <notifications@github.com>:

**Comment by joel16** [comment]
Thanks for confirming, I'll re-upload the latest release for the original version in a bit.
