### ISSUE TITLE
Incorrect model listing

### ISSUE THREAD

**Issue by Masamune3210** [joel16/3DSident#12]
System listed as N3DS XL RED, but system is actually N3DS XL NEW GALAXY EDITION

**Comment by joel16** [comment]
Lol, RED is the code name for N3DS XL. It isn't determining the colour.

https://3dbrew.org/wiki/Cfg:GetSystemModel#System_Model_Values

**Comment by Masamune3210** [comment]
Lol sorry forgot that RED was the codename, that's what happens when codenames are normal words
