### ISSUE TITLE
Add a tab to show the current CPU speed/L2 status.

### ISSUE THREAD

**Issue by nl255** [joel16/3DSident#13]
I would like to be able to see the current cpu speed/l2 cache settings in 3dsident.  This could probably be done by removing the "New3DS Exclusive Process Settings" section so that it will only run at 804mhz or with l2 cache enabled if that is forced as well as displaying the current cpu mode and whether l2 cache is accessible.  This would be useful for making sure the "overclock" options work properly, both in the boot config as well as in the Rosalina menu.

**Comment by joel16** [comment]
IIRC there isn't any function that can check the current clock speed. If there is (I don't think anyone has reversed it yet, and I'm not planning on doing that).

However, if you're running 3DSident under a new 3DS it automatically sets the New 3DS speed boost (only on the GUI).

**Comment by nl255** [comment]
Yet Luma is able to tell somehow and apparently it even does so correctly when clock+l2 is not forced yet you run a n3ds exclusive game like snes vc or xenoblade.

**Comment by joel16** [comment]
My bad, it was around 3 AM when I replied there. I assumed Roslania used luma's config to determine the n3DS clock speed, but seems like it doesn't when I asked TuxSH. This commit should take care of it:
https://github.com/joel16/3DSident/commit/00aa57846c22120962b5cf621e422d8957ca39ba
