### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by Hellrespawn** [joel16/3DSident#15]
In the GUI version "Miscellaneous" is incorrectly spelled "Miscelleanous."

**Comment by joel16** [comment]
Oh no how could I possibly call myself a grammar nazi when I've misspelled such a common word. Thanks for letting me know about this, I'll do it in a bit.

**Comment by joel16** [comment]
https://github.com/joel16/3DSident/commit/ec86f6c561fbc875593fb10e6623f8df21c33d1c
