### ISSUE TITLE
Protect 3DSident with parental control

### ISSUE THREAD

**Issue by zhanxjxx** [joel16/3DSident#17]
HB launcher and FBI has this. Considering that 3DSident reveals a lot of sensitive information, would it be possible to add that to the CIA version?

**Comment by joel16** [comment]
Well, you see the new parental control info was actually added to allow people to get around that incase they forget their pin code or something. At most I could probably send you a custom build that asks for a pin code to launch 3DSident.

**Comment by zhanxjxx** [comment]
Ah I see, a custom build would be great, really like your work!

**Comment by joel16** [comment]
No worries! Wasn't sure which version you preferred so I did both. Make sure you delete the title first before installing the .CIA or else the pin code prompt won't show up.

[Original](https://drive.google.com/open?id=0BzIzEQt6k4EEMV9aaUZvcTIzVGM)
[GUI](https://drive.google.com/open?id=0BzIzEQt6k4EEN3FOMV83LU5JLWM)

I've enabled parental control settings just to check if they're working and it did on my device, please let me know how it goes.

**Comment by zhanxjxx** [comment]
Both of them work, thanks a lot!
