### ISSUE TITLE
When SM/FS is unpatched, .3dsx version crashes when changing selection from WiFi Information to another row (GUI)

### ISSUE THREAD

**Issue by ImmortalScientist** [joel16/3DSident#18]

**Comment by joel16** [comment]
Yeah I'm working on one final release to solve these issues.
This time it'll check if the functions that require the sm/fs patch can run successfully, if it doesn't it'll display 0 or NULL.

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/3DSident/commit/624c305ba8c5d0059387366f44f64691d33f3e9c

Seems like this service cannot be accessed when running under *hax. Therefore a message saying "This service cannot be accessed in *hax." will be displayed to avoid crashes.
