### ISSUE TITLE
Crashes when looking at Storage tab if SD removed

### ISSUE THREAD

**Issue by Aluminite** [joel16/3DSident#19]
Best way to test this is to inject it to Health and Safety. Open it from H&S, and remove the SD card. It will work normally. Select the `Storage Information` tab and it will either freeze the whole system or have an exception.

Tested using a n2dsxl on 11.6

(This is in GUI by the way)

**Comment by joel16** [comment]
Of course it freezes, its running off the SD and you removed it. Its gonna stop working, do that with a installed game and tell me the results.

**Comment by Aluminite** [comment]
You're missing the point. If you inject 3dsident to h&s, then launch h&s with the SD removed, it works fine. If you choose the storage tab it crashes the whole system.
