### ISSUE TITLE
Screen brightness level is not represented correctly

### ISSUE THREAD

**Issue by PokeCaptain** [joel16/3DSident#20]
System info:
- Model: n3DS XL
- Region: USA
- SYS VER: 11.6
- Luma Ver: 8.1.1
- Bootloader: B9S

According to [hardware.c](https://github.com/joel16/3DSident/blob/master/source/hardware.c), the brightness level is determined by the following:

	char * getBrightness(u32 screen)
	{
	u32 brightness = 0;
	if(R_SUCCEEDED(gspLcdInit()))
	{
		if (R_SUCCEEDED(GSPLCD_GetBrightness(screen, &brightness)))
			gspLcdExit();
	}
	if (brightness == 0x10)
		return "1 (20%)";
	else if (brightness == 0x1C)
		return "2 (40%)";
	else if (brightness == 0x30)
		return "3 (60%)";
	else if (brightness == 0x52)
		return "4 (80%)";
	else if (brightness == 0x8E)
		return "5 (100%)";
	else
		return "n3DS only";
        }

This code seems to report the brightness percentage based off of the current brightness setting (1-5) in the Home Menu pop-up. However, this code does not seem to take into account the Auto Brightness setting, which doesn't choose brightness levels on 20% intervals. Because of the logic in the code, the brightness level in 3DSident almost always reads "n3DS only", even though the device is an n3DS. This issue may also be triggered by the "Power-Saving mode".

**Comment by joel16** [comment]
Should be fixed in the commit: https://github.com/joel16/3DSident/commit/9305119a52b26334789e80e96f314f7a580bb4b5

I'm not sure why I was even doing it like that in the first place. I assumed it only gave you values using 20% increments, at least that's what the documentation provided on 3dbrew made it seem like. Anyways I'll send a build in a few minutes, can you verify that it works once I have sent it?

**Comment by joel16** [comment]
Alright here, can you try this and tell me if this makes it any better? It also displays if auto brightness is enabled and if power saving mode is enabled (battery menu).

https://drive.google.com/open?id=0BzIzEQt6k4EEV2ZzT3Y1eGxkT1U

**Comment by PokeCaptain** [comment]
Just got around to testing it. Brightness levels are now represented correctly. Auto brightness and power saving mode are both correctly represented as well. Might want someone to test this on an o3DS as well, as I don't have one atm.

**Comment by joel16** [comment]
Seems like the GSP's brightness functions are stubbed on old3ds so this will have to be a New 3DS exclusive feature. Well thanks for reporting and testing!
