### ISSUE TITLE
I encountered the following error when building, how to solve it?

### ISSUE THREAD

**Issue by qianxuu** [joel16/3DSident#27]
### qianxu@qianxu-VirtualBox:~/桌面/3dsident-i18n-zh-cn$ make
make[1]: 进入目录“/home/qianxu/桌面/3dsident-i18n-zh-cn/console”
system.c
/home/qianxu/桌面/3dsident-i18n-zh-cn/console/../common/system.c: In function 'System_GetNANDLocalFriendCodeSeed':
/home/qianxu/桌面/3dsident-i18n-zh-cn/console/../common/system.c:252:9: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  252 |  buf[6] = '\0';
      |  ~~~~~~~^~~~~~
/home/qianxu/桌面/3dsident-i18n-zh-cn/console/../common/system.c:213:22: note: at offset 6 to an object with size 0 allocated by 'malloc' here
  213 |  char *buf = (char *)malloc(6);
      |                      ^~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:85：system.o] 错误 1
make[1]: *** [Makefile:207：all] 错误 2
make[1]: 离开目录“/home/qianxu/桌面/3dsident-i18n-zh-cn/console”
make[1]: 进入目录“/home/qianxu/桌面/3dsident-i18n-zh-cn/gui”
system.c
/home/qianxu/桌面/3dsident-i18n-zh-cn/gui/../common/system.c: In function 'System_GetNANDLocalFriendCodeSeed':
/home/qianxu/桌面/3dsident-i18n-zh-cn/gui/../common/system.c:252:9: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  252 |  buf[6] = '\0';
      |  ~~~~~~~^~~~~~
/home/qianxu/桌面/3dsident-i18n-zh-cn/gui/../common/system.c:213:22: note: at offset 6 to an object with size 0 allocated by 'malloc' here
  213 |  char *buf = (char *)malloc(6);
      |                      ^~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:85：system.o] 错误 1
make[1]: *** [Makefile:207：all] 错误 2
make[1]: 离开目录“/home/qianxu/桌面/3dsident-i18n-zh-cn/gui”
make: *** [Makefile:4：all] 错误 2
qianxu@qianxu-VirtualBox:~/桌面/3dsident-i18n-zh-cn$

**Comment by joel16** [comment]
This hasn't been built for over 2 years. I'd suggest removing the "-Werror" cflag from the makefile and see if it still compiles. It will still produce warnings however. This honestly has a lot of room for improvement.

**Comment by qianxuu** [comment]
> This hasn't been built for over 2 years. I'd suggest removing the "-Werror" cflag from the makefile and see if it still compiles. It will still produce warnings however. This honestly has a lot of room for improvement.

Thank you. But I encountered a new error.

### qianxu@qianxu-VirtualBox:~/桌面/3DSident$ make
make[1]: 进入目录“/home/qianxu/桌面/3DSident/console”
main.c
hardware.c
system.c
/home/qianxu/桌面/3DSident/console/../common/system.c: In function 'System_GetNANDLocalFriendCodeSeed':
/home/qianxu/桌面/3DSident/console/../common/system.c:252:9: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  252 |  buf[6] = '\0';
      |  ~~~~~~~^~~~~~
/home/qianxu/桌面/3DSident/console/../common/system.c:213:22: note: at offset 6 to an object with size 0 allocated by 'malloc' here
  213 |  char *buf = (char *)malloc(6);
      |                      ^~~~~~~~~
storage.c
utils.c
misc.c
wifi.c
kernel.c
fs.c
ac.c
am.c
actu.c
linking 3DSident.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: kernel.o:/home/qianxu/桌面/3DSident/console/../common/fs.h:6: multiple definition of `archive'; system.o:/home/qianxu/桌面/3DSident/console/../common/fs.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: fs.o:/home/qianxu/桌面/3DSident/console/../common/fs.h:6: multiple definition of `archive'; system.o:/home/qianxu/桌面/3DSident/console/../common/fs.h:6: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [/opt/devkitpro/devkitARM/3ds_rules:42：/home/qianxu/桌面/3DSident/console/3DSident.elf] 错误 1
make[1]: *** [Makefile:207：all] 错误 2
make[1]: 离开目录“/home/qianxu/桌面/3DSident/console”
make[1]: 进入目录“/home/qianxu/桌面/3DSident/gui”
sprites.t3s
C2D_helper.c
menus.c
config.c
main.c
menu_control.c
textures.c
hardware.c
system.c
/home/qianxu/桌面/3DSident/gui/../common/system.c: In function 'System_GetNANDLocalFriendCodeSeed':
/home/qianxu/桌面/3DSident/gui/../common/system.c:252:9: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  252 |  buf[6] = '\0';
      |  ~~~~~~~^~~~~~
/home/qianxu/桌面/3DSident/gui/../common/system.c:213:22: note: at offset 6 to an object with size 0 allocated by 'malloc' here
  213 |  char *buf = (char *)malloc(6);
      |                      ^~~~~~~~~
storage.c
utils.c
misc.c
wifi.c
kernel.c
fs.c
ac.c
am.c
actu.c
linking 3DSident-GUI.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/common.h:8: multiple definition of `exitJmp'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/common.h:8: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `sizeBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `dynamicBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `staticBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_BOTTOM'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menus.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_TOP'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `volumeIcon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `cursor'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_home'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cstick'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Dpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZR'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZL'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_R'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_L'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Start_Select'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Y'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_X'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_B'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_A'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `drive_icon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `banner'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/common.h:8: multiple definition of `exitJmp'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/common.h:8: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `sizeBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `dynamicBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `staticBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_BOTTOM'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: main.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_TOP'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `volumeIcon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `cursor'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_home'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cstick'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Dpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZR'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZL'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_R'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_L'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Start_Select'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Y'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_X'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_B'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_A'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `drive_icon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `banner'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `sizeBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `dynamicBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: multiple definition of `staticBuf'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:16: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_BOTTOM'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: menu_control.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: multiple definition of `RENDER_TOP'; C2D_helper.o:/home/qianxu/桌面/3DSident/gui/include/C2D_helper.h:15: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `volumeIcon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `cursor'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_home'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cstick'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Cpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Dpad'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZR'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_ZL'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_R'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_L'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Start_Select'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_Y'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_X'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_B'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: multiple definition of `btn_A'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:7: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `drive_icon'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: textures.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: multiple definition of `banner'; menus.o:/home/qianxu/桌面/3DSident/gui/include/textures.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: kernel.o:/home/qianxu/桌面/3DSident/gui/../common/fs.h:6: multiple definition of `archive'; system.o:/home/qianxu/桌面/3DSident/gui/../common/fs.h:6: first defined here
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: fs.o:/home/qianxu/桌面/3DSident/gui/../common/fs.h:6: multiple definition of `archive'; system.o:/home/qianxu/桌面/3DSident/gui/../common/fs.h:6: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [/opt/devkitpro/devkitARM/3ds_rules:42：/home/qianxu/桌面/3DSident/gui/3DSident-GUI.elf] 错误 1
make[1]: *** [Makefile:207：all] 错误 2
make[1]: 离开目录“/home/qianxu/桌面/3DSident/gui”
make: *** [Makefile:4：all] 错误 2
qianxu@qianxu-VirtualBox:~/桌面/3DSident$

**Comment by joel16** [comment]
Some variable probably redefined somewhere. I don't really maintain this anymore.
