### ISSUE TITLE
(3DSident v0.8.0 - Final GUI) CIA crashing on exit

### ISSUE THREAD

**Issue by saint-etienne** [joel16/3DSident#28]
Crashes on exit (with crash dump)
Same as previous post from 2017: https://github.com/joel16/3DSident/issues/7

Original cia _3DSident.cia_ works fine, though.

Entrypoint: HBlauncher_Loader 1.3
System: Old3DS version 11.14. 0-46 w/ Luma v10.2.1
3DSident v0.8.0 - Final (GUI version) - 3DSident-GUI.cia

**Comment by Wsx199797** [comment]
none yet

**Comment by joel16** [comment]
Please use https://github.com/joel16/3DSident/releases/tag/0.9.0
