### ISSUE TITLE
Only White Screen when starting - App still working?

### ISSUE THREAD

**Issue by Friday13th87** [joel16/3DSident#30]
Hello there,
i tried using 3DSident and installed the gui version 0.8 to my Luma3DS CFW  "11.15.0-47E"
When i am starting the Application the 3DSident logo shows up and afterwards i am only getting white screens on both displays.
Is there any workaround?
I installed the app via cia file in FBI, via QR Code in FBI and via uni-store with the exact same result.

Is the App still working with the newer Firmwares?

I actually only wanted to check if i hafe IPS Panels installed - is there any other way do get those details displayed?
Thanks!

**Comment by joel16** [comment]
Can you try the console version?

**Comment by Friday13th87** [comment]
The non-gui version is starting, showing some informations for a milli second and then aborting with
"An exeption occured
Exeption Type: prefetch abort
Fault status: Translation - Section"

same is happening with the 3dx versions in the homebrew channel

my console is running in english and i already checked the microsd with F3 under debian.


PS: if i am starting the gui version, the console is not freezing, i still can hit the home button and close the app. after closing the app, the same error of the non-gui version is showing up.

PPS: found that thread and in the very last post, the person describes the same behavior as i (i think)
https://gbatemp.net/threads/release-3dsident.435755/page-17

PPPS: v0.7.7 nono-gui console Version is working via homebrew channel (3dsx) - v 0.78 gui/non-gui cia is not working as well, didnt tried more versions

**Comment by joel16** [comment]
Weird, this wasn't a problem when I last released these. I don't know what's changed (luma updates?), you can try re-compiling to see if it helps. I don't know where my 3ds is anymore so it might be a while till I can look into this.

**Comment by shaniacorbishley2** [comment]
Can confirm I had this issue too, I followed friday13th advice on v0.7.7 and it’s working only on this version. My old new 3ds xl however worked fine using the latest.

**Comment by RedowskyX5** [comment]
Same here. Still wondering where's the problem and how to fix it, cuz i got my new 3ds xl lately. Weird part is that my old 3ds xl can and will run 3Dsident perdectly fine.

**Comment by joel16** [comment]
> Same here. Still wondering where's the problem and how to fix it, cuz i got my new 3ds xl lately. Weird part is that my old 3ds xl can and will run 3Dsident perdectly fine.

Sorry for the late response. I don't have access to a 3DS near me, but I was working on re-writing this app and in C++. However, I don't really get much time to work on homebrew these days, and would have to rely on testers.

**Comment by joel16** [comment]
Closing this with https://github.com/joel16/3DSident/releases/tag/0.9.0
