### ISSUE TITLE
Closing 3DSident GUI causes the 3DS to crash

### ISSUE THREAD

**Issue by ghost** [joel16/3DSident#31]
When you Close the Software (using the Home Menu) while displaying Battery Information the 3DS will Crash.

(See Screenshot)

![IMG_20220720_182330133~2](https://user-images.githubusercontent.com/109685325/180033768-fb8990a0-96ff-4f0f-87ff-889635d082a3.jpg)

old3DS XL Sys 11.15.0-47E
CIA Version of 3DSident GUI v0.8.0

**Comment by joel16** [comment]
This should be fixed with https://github.com/joel16/3DSident/releases/tag/0.9.0
