### ISSUE TITLE
Should this work on New 3DS XL?

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [joel16/3DSident#32]
Hi, 

Should this work on New 3DS XL?

I'm assuming not because it just crashes, but I could see anywhere that explicitly says it doesn't

**Comment by Minionguyjpro** [comment]
> Hi,
> 
> Should this work on New 3DS XL?
> 
> I'm assuming not because it just crashes, but I could see anywhere that explicitly says it doesn't

I guess it should work. I have a New 2DS XL and it runs perfectly fine. A friend I know has a New 3DS XL and it also works there. Maybe there is something wrong at your side?
