### ISSUE TITLE
QR code images in the “Releases” page are broken 

### ISSUE THREAD

**Issue by superrpotion** [joel16/3DSident#33]
https://github.com/joel16/3DSident/releases

The QR codes under “Original” and “GUI” are broken images. 

Screenshot of the broken images:
![IMG_8337](https://github.com/user-attachments/assets/499e1158-71bb-4699-a00b-f1f7a57e4d05)

**Comment by joel16** [comment]
Unfortunately cia builds are no longer supported, please use the latest release: https://github.com/joel16/3DSident/releases/tag/0.9.0
