### ISSUE TITLE
Discrepancy with the Check Digit in the SN

### ISSUE THREAD

**Issue by JWelsh97** [joel16/3DSident#35]
I discovered that the check digit on 3DSident didn't match the one my device had. So I manually calculated it myself and found that it is wrong in 3DSident. 

I took the value of the evens and multiplied them by 3 and then add the value of the odds to that number which gave me 51, then I did 51 modulo 10  which gives me 1, subtract that from 10 and that gives me 9 which is correct on the SN Label but in 3DSident it says the check digit is 7.

Unfortunately I don't have enough knowledge to fix the function code or I would.

**Comment by joel16** [comment]
Can you send me your serial so I can run it against the function that calculates the check digit so I can try to identify the issue?

**Comment by JWelsh97** [comment]
I have a little bit of background in Python so I decided to have a look and what seems to be happening is odd indices are being placed as even and even indices as odd. This should fix the issue:

`for (size_t i = 1; i < 10; ++i) {
        int digit = serialNumber[i] - '0'; 
        if (i % 2 == 1)    { 
            oddSum += digit;`

So now the loop starts at 1

**Comment by JWelsh97** [comment]
> Can you send me your serial so I can run it against the function that calculates the check digit so I can try to identify the issue?

Thanks for the quick reply. As noted in my comment I think it's a little mix up with the odd and even indices, but just for you to check my serial is 11138186 and on the label the check digit is 9 but 3DSident is showing the check digit as 7.

**Comment by joel16** [comment]
Thank you! I'll have a look at this and publish a hot fix once confirmed.

**Comment by joel16** [comment]
> > Can you send me your serial so I can run it against the function that calculates the check digit so I can try to identify the issue?
> 
> Thanks for the quick reply. As noted in my comment I think it's a little mix up with the odd and even indices, but just for you to check my serial is 11138186 and on the label the check digit is 9 but 3DSident is showing the check digit as 7.

Hmm, I tried this with the current 3DSident algorithim and I got 9 back as the check digit. I assume your serial has two letters at the front like so -> CW11138186. Perhaps not all serials have two letters, can you send me your full serial including the letters?

**Comment by JWelsh97** [comment]
> > > Can you send me your serial so I can run it against the function that calculates the check digit so I can try to identify the issue?
> > 
> > 
> > Thanks for the quick reply. As noted in my comment I think it's a little mix up with the odd and even indices, but just for you to check my serial is 11138186 and on the label the check digit is 9 but 3DSident is showing the check digit as 7.
> 
> Hmm, I tried this with the current 3DSident algorithim and I got 9 back as the check digit. I assume your serial has two letters at the front like so -> CW11138186. Perhaps not all serials have two letters, can you send me your full serial including the letters?

Ahh yes I think that's it, my serial number is QEH11138186. That makes sense now

**Comment by joel16** [comment]
> > > > Can you send me your serial so I can run it against the function that calculates the check digit so I can try to identify the issue?
> > > 
> > > 
> > > Thanks for the quick reply. As noted in my comment I think it's a little mix up with the odd and even indices, but just for you to check my serial is 11138186 and on the label the check digit is 9 but 3DSident is showing the check digit as 7.
> > 
> > 
> > Hmm, I tried this with the current 3DSident algorithim and I got 9 back as the check digit. I assume your serial has two letters at the front like so -> CW11138186. Perhaps not all serials have two letters, can you send me your full serial including the letters?
> 
> Ahh yes I think that's it, my serial number is QEH11138186. That makes sense now

That is definitely it, the current algorithm always assumes there's 2 letters hence why it's failing. I'll try to get this sorted once I'm home. Thanks!

**Comment by joel16** [comment]
This should fix it, I'll publish a new release soon: https://github.com/joel16/3DSident/commit/8ff0c2407721a4cbccec23c60b61941f25c468f3
