### ISSUE TITLE
Attempting to open Rosalina while 3dsident is running = hard crash

### ISSUE THREAD

**Issue by shinji257** [joel16/3DSident#9]
I tested this with other cia installed homebrew just in case.  Seems isolated so I'm reporting this here.

Firmware: 11.4.0-37U
CFW: Luma 3DS 8.0
Boot Method: Boot9Strap 1.2
Application version: 0.7.4 GUI version

Steps:
1. Open 3DSident 0.7.4 GUI
2. Attempt to open the Rosalina menu

Expected results: Rosalina opens
Actual results: Bottom screen goes black then the whole system hard locks

This was actually discovered while the application was suspended at the home screen.  It happens regardless if the app is suspended or not.  It does not happen if the app is not running at all.

I do not get a crash dump from the system.

**Comment by joel16** [comment]
Thanks for reporting, will look into this.

**Comment by joel16** [comment]
Considering the amount of things Luma has been fucking up recently, I'm not going to be bother fixing this. Sorry about that.
